// utils/emailTypes.js
const EmailTypes = {
  FORGOT_PASSWORD: "FORGOT_PASSWORD",
  RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
  CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
};

module.exports = EmailTypes;
